variables:
  GIT_DEPTH: 1000

stages:
  - build
  - test

win_build:
  stage: build
  tags:
    - visualstudio
    - windows
  script:
    - ./build_release.cmd
  artifacts:
    name: "%CI_JOB_STAGE%-%CI_COMMIT_REF_NAME%"
    paths:
      - build-release/bin/Release
      - build-release/u3WindowsManagerApp-*.zip


win_test:
  stage: test
  tags:
    - visualstudio
    - windows
  dependencies:
    - win_build
  script:
    - ./build_release_test.cmd
  artifacts:
    when: always
    reports:
      junit: TestResult.xml

