variables:
  GIT_DEPTH: 1000

stages:
  - build
  - test
  - package

win_build:
  stage: build
  tags:
    - visualstudio
    - windows
  script:
    - ./build_release.cmd
  artifacts:
    paths:
      - build-release/


win_test:
  stage: test
  tags:
    - visualstudio
    - windows
  dependencies:
    - win_build
  script:
    - ./build_release_test.cmd
  artifacts:
    when: always
    reports:
      junit: TestResult.xml


include: 'build-release/build_info.yml'
win_package:
  stage: package
  tags:
    - visualstudio
    - windows
  dependencies:
    - win_build
  script:
    - ./build_release_package.cmd
  artifacts:
    paths:
      - build-release/$PACKAGE_NAME-$PACKAGE_VERSION-$PACKAGE_ARCH.msi
