variables:
  GIT_DEPTH: 1000

stages:
  - build
  - test
  - package

win_build:
  stage: build
  tags:
    - visualstudio
    - windows
  script:
    - ./build_release.cmd
  artifacts:
    name: "$env:CI_JOB_STAGE-$env:CI_COMMIT_REF_NAME"
    paths:
      - build-release/bin/Release/


win_test:
  stage: test
  tags:
    - visualstudio
    - windows
  dependencies:
    - win_build
  script:
    - ./build_release_test.cmd
  artifacts:
    when: always
    reports:
      junit: TestResult.xml


win_package:
  stage: package
  tags:
    - visualstudio
    - windows
  dependencies:
    - win_build
  script:
    - ./build_release_package.cmd
  artifacts:
    paths:
      - build-release/u3WindowsManager-*.msi
